config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  
  get '/reviews' => 'reviews#new', as: :new_review
  get 'reviews/:id/edit' => 'reviews#edit', as: :edit_review
  root 'sessions#index'

  get '/reviews' => 'reviews#index' 
  get '/login' => 'sessions#new', as: :sessions
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :log_out
  
  get 'users/new' => 'users#new'
  post 'users/' => 'users#create'

  get '/signup' => 'users#new', as: :signup

end

app/models/review.rb
class Review
  include Mongoid::Document 
  field :name, type: String
  field :email, type: String
  field :rating, type: Float
  field :restaurant, type: String
  field :comment, type: String
end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  attr_reader :password

  def password=(new_password)
  	self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
  	if test_password && BCrypt::Password.new(self.password_digest) == test_password
  		self
  	else
  		false
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
	@reviews = Review.all
  end

  def show 
  @review = Review.find(params[:id]) 
  @reviews = Review.all
  end

  def index
    @review = Review.new
    @reviews = Review.all
  end


  def new
  	@review = Review.new
  end

  def create
  	@review = Review.new(params.require(:review).permit(:name, :email, :rating, :restaurant, :comment))
  	if @review.save
  		redirect_to new_review_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@review = Review.find(params[:id])
  end

  def update
  	@review = Review.find(params[:id])
  	if @review.update_attributes(params.require(:review).permit(:name, :email, :rating, :restaurant))
  		redirect_to index_path
  	else
  		render 'edit'
  	end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	flash.clear
  end

  def create
  	flash.clear
  	begin
  		user = User.find_by({email: params[:session][:email]})
  	rescue
  		flash[:error] = 'Email not found'
  	end

  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		redirect_to reviews_path
  	else
  		flash[:error] ||= 'Try Again!'
  		render 'new'
  	end
  end
  def destroy

  	log_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params.require(:user).permit(:name, :email, :password))
  	if @user.save
  		#log the user in
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#log in: set user ID cookie in user's browser
	def log_in(user)
		cookies.permanent[:cookie_id] = user.id

		@current_user = user
	end
	#LOG OUT: remove cookies from user's browser
	def log_out
		cookies.delete(:cookie_id)

	end

	#true if user logged in
	def logged_in?
		cookies[:cookie_id] ? true : false

	end

	#If not already set, retrieve user from MongoDB
	def current_user
		if logged_in?
			@current_user ||= User.find(cookies[cookie_id])
		else
			nil
		end
	end

	#current_user Setter (similar to attr_writer)
	def current_user=(user)
		@current_user = user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opinionated</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/edit.html.erb
<h1> Make changes to your review </h1>

<%= form_for @review do |f| %>
	Name: <%= f.text_field :name %>
	Email <%= f.text_field :email %>
	Rating <%= f.text_field :rating %>
	Restaurant <%= f.text_field :restaurant %>

	<%=f.submit 'Make Changes' %>

	<% end %>

	<%= link_to 'Back to the Homeland', reviews_path %> 

app/views/reviews/index.html.erb
<h1> Tell us about your experiences </h1>

	


	<% @reviews.each do |r| %>
	  <%= r.name %> <br>
	  <%= r.rating %> 
	  <%= r.restaurant %> <br>
	  <%= r.comment %> <hr> 

	<% end %>

	<%= link_to "Home",  new_review_path %>
	<style>
	body{
	font-family: calibri light;</style>
 
 

app/views/reviews/new.html.erb
<nav>Welcome to Opinionated <div id="1" >About US</div> Contact Us Location Sign in</nav>
<p>This place sucks
	<br>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots<br> in a piece of classical Latin literature from 45 BC, making it over 2000 years old.<br> Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,<br> looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum<br> passage, and going through the cites of the word in classical literature, discovered<br> the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33<br> of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,<br> written in 45 BC. This book is a treatise on the theory of ethics, very popular<br> during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor<br> sit amet..", comes from a line in section 1.10.32.
this place really sucks Contrary to popular<br> belief, Lorem Ipsum is not simply random text. It has roots<br> in a piece of classical Latin literature from 45 BC, making it over 2000 years old.<br> Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,<br> looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum<br> passage, and going through the cites of the word in classical literature, discovered<br> the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33<br> of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,<br> written in 45 BC. This book is a treatise on the theory of ethics, very popular<br> during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor<br> sit amet..", comes from a line in section 1.10.32.
this place really sucks</p>

<div id="form">
<%= form_for @review do |f| %>
	Name: <%= f.text_field :name %> <br><br>
	Email <%= f.text_field :email %> <br><br>
	Rating <%= f.text_field :rating %><br><br>
	Restaurant <%= f.text_field :restaurant %> <br><br>
	<div id ="C">Comment <%= f.text_area :comment %></div>
</div>

	<div id="submit"><%= f.submit  "Submit your review" %></div>

	<div id="ET"><%= link_to "Edit time!", edit_review_path(f) %></div>


	<% end %>

	<div id="sub"><%= link_to "Check out others reviews", reviews_path %> </div>

<button id="btn">This is a hidden message</button>

<style>
	body{
		background-color: rgba(140, 0 , 26, 1);
		background-image: image-url("kitchen.jpg");
	}
	p{
	  color: transparent;
      text-shadow: 0 0 5px rgba(0,0,0,5);
      float: left;
	}
	#submit{
		float:right;
	}
	#sub{
		float:right;
		padding:10px;
		
	}
	#ET{
		float: right;
		padding:10px;
		color:red;
	}
	#form{
		float:right;padding:30px;
	}
	#c{
		float: right;
	}
	nav{
		float:right;
		color: white;
		padding: 20px;
		background-color: navy;
		width: 100%;
		margin: -10px;
		text-align: center;
		display: inline block;
}
input[type=text], textarea {
  -webkit-transition: all 0.30s ease-in-out;
  -moz-transition: all 0.30s ease-in-out;
  -ms-transition: all 0.30s ease-in-out;
  -o-transition: all 0.30s ease-in-out;
  outline: none;
  padding: 3px 0px 3px 3px;
  margin: 5px 1px 3px 0px;
  border: 1px solid #DDDDDD;
}
 
input[type=text]:focus, textarea:focus {
  box-shadow: 0 0 5px rgba(81, 203, 238, 1);
  padding: 3px 0px 3px 3px;
  margin: 5px 1px 3px 0px;
  border: 1px solid rgba(81, 203, 238, 1);
}
</style>

app/views/reviews/show.html.erb
<h1> <%= @review.name %> </h1>

  <p>This review is a review for <%= @review.name %> 
  	, <br> and I gave it a score of <%= @review.rating %>,
  	<%= @review.restaurant %> </p>

    <%= link_to "Back to the reviews!", reviews_path %>

    <%= link_to "Delete your review", @review, method: :delete, data: { confirm: 'Are you sure you want to abandon all hope?'} %>

app/views/users/new.html.erb
<h1 id="SI">Sign Up!</h1>

<div class="Sign_up">
<%= form_for @user do |f| %>
	<div id="name"><%= f.label :name %>
	<%= f.text_field :name %></div><br>

	<div id="email"><%= f.label :email %><div class="EM">
	<%= f.text_field :email %></div></div><br>

	<div id ="password"><%= f.label :password %>
	<%= f.text_field :password %></div>


	<%= f.submit "Sign Me Up!" %>
	</div>
<% end %>

<style>
	.Sign_up{
		text-align: center;
		font-size: 25pt;
		

	}
	#SI{
		text-align: center;
		rotate(-90deg);
	}
</style>